services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.cloud.erickweyunga.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"
